name = "Quantikz"
uuid = "b0d11df0-eea3-4d79-b4a5-421488cbf74b"
authors = ["Stefan Krastanov <stefan@krastanov.org>"]
version = "0.4.0-DEV"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
Tectonic = "9ac5f52a-99c6-489f-af81-462ef484790f"

[compat]
julia = "1.3"
Suppressor = "0.2"
Tectonic = "0.4"